<?php

namespace AppBundle\Repository;

/**
 * BlockedIPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockedIPRepository extends \Doctrine\ORM\EntityRepository
{
}
