<?php

namespace AppBundle\Repository;

/**
 * GeolocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeolocationRepository extends \Doctrine\ORM\EntityRepository
{
}
