<?php

namespace AppBundle\Repository;

/**
 * GeoliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoliteRepository extends \Doctrine\ORM\EntityRepository
{
}
