<?php

namespace AppBundle\Repository;

/**
 * GeoliteIpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoliteIpRepository extends \Doctrine\ORM\EntityRepository
{
}
