<?php

namespace AppBundle\Repository;

/**
 * SchoolLiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolLiveRepository extends \Doctrine\ORM\EntityRepository
{
}
