<?php

namespace AppBundle\Repository;

/**
 * SearchCriteriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchCriteriaRepository extends \Doctrine\ORM\EntityRepository
{
}
