<?php

namespace AppBundle\Repository;

/**
 * UserPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPhotoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPictures($limit = 1000, $offset = 0, $property = null, $order = null, $uid = null)
    {
        $qb = $this->createQueryBuilder('u');

        if($uid){
            $qb->where('u.user = '.$uid);
        }

        if($property && $order){
            $qb->orderBy('u.'.$property, $order);
        }

        return $qb->getQuery()->setMaxResults($limit)->setFirstResult($offset)->getResult();
    }

    public function findUserPictures($userId)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->where('u.user = '.$userId);

        $qb->select('u.id');

        return $qb->getQuery()->getResult();
    }
}
